
GET http://localhost:3001/api/user

### Create User
POST http://localhost:3001/api/user
Content-Type: application/json

{
    "name": "Mauricio Duran",
    "username": "mduran",
    "password": "1234100"
}

### User Login
POST http://localhost:3001/api/user/login
Content-Type: application/json

{
    "username": "mduran",
    "password": "1234100"
}

### Get user Tasks (Requires token)
GET  http://localhost:3001/api/task
Content-Type: application/json
Authorization: 

### Get task by Id  (Requires token and that the task belongs to the user)
GET  http://localhost:3001/api/task/:id
Content-Type: application/json
Authorization: 

### Create Task (Requires token)
POST http://localhost:3001/api/task
Content-Type: application/json
Authorization: 

{
    "title": "Terminar WebApp NextLine",
    "description": "Documentar frontend y backend de la application de task management de Nextline",
    "dateOfDelivery": "2021-12-5T17:39:36.610Z",
    "comments": "Vamos por buen camino",
    "responsiblePerson": "Mau",
    "tags": ["interview", "nextLine"]
}

### Update Task (Requires token and that the task belongs to the user)
PUT http://localhost:3001/api/task/:id
Content-Type: application/json
Authorization: 

{
    "title": "Terminar WebApp TaskManager"
}

### Delete Task (Requires token and that the task belongs to the user)
DELETE   http://localhost:3001/api/task/:id
Content-Type: application/json
Authorization: 
