const NotificationActionTypes = {
    OPEN_SUCCESS_NOTIFICATION_START: "OPEN_SUCCESS_NOTIFICATION_START",
    OPEN_ERROR_NOTIFICATION_START: "OPEN_ERROR_NOTIFICATION_START",
    OPEN_SUCCESS_NOTIFICATION: "OPEN_SUCCESS_NOTIFICATION",
    OPEN_ERROR_NOTIFICATION: "OPEN_ERROR_NOTIFICATION",
    CLOSE_NOTIFICATION: "CLOSE_NOTIFICATION",
}

export default NotificationActionTypes;


