const TaskActionTypes = {
    FETCH_TASK_START: 'FETCH_TASK_START',
    FETCH_TASK_SUCCESS: 'FETCH_TASK_SUCCESS',
    FETCH_TASK_FAILURE: 'FETCH_TASK_FAILURE',
    FETCH_TASKS_START: 'FETCH_TASKS_START',
    FETCH_TASKS_SUCCESS: 'FETCH_TASKS_SUCCESS',
    FETCH_TASKS_FAILURE: 'FETCH_TASKS_FAILURE',
    CREATE_TASK_START: 'CREATE_TASK_START',
    CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
    CREATE_TASK_FAILURE: 'CREATE_TASK_FAILURE',
    UPDATE_TASK_START: 'UPDATE_TASK_START',
    UPDATE_TASK_FAILURE: 'UPDATE_TASK_FAILURE',
    UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',
    DELETE_TASK_START: 'DELETE_TASK_START',
    DELETE_TASK_FAILURE: 'DELETE_TASK_FAILURE',
    DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
    CLOSE_ERROR_DIALOG: 'CLOSE_ERROR_DIALOG',
}

export default TaskActionTypes;


